### This notebook introduces you to concepts of vectors for Machine Learning using Numpy libraray. 

Vectors are array which have magnitude and direction. In a 2-d co-ordinate system they are simply a point having x and y values. 


In [8]:
import numpy as np

In [7]:
v1 = np.array([1,2])

In [21]:
print(v1)
print('Length of vector={}'.format(len(v1)))
print('Shape of vector={}'.format(v1.shape))

[1 2]
Length of vector=2
Shape of vector=(2,)


### Vector Addition

Vector addition adds corresponding components from both vectors. Vector addtion doesn't work if shape of two vectors are NOT same. 

In [25]:
v2 = np.array([4,5])

In [24]:
v1+v2

array([5, 7])

### Scalar Multiplication

It basically scales all components of the vector by that value; i.e it multiplies all elements of the vector by the scalar. 

In [30]:
2*v1

array([2, 4])

### Dot Product (or Dot Product)

We represent it by placing a dot.

A dot product is a scalar value that is the result of an operation of two vectors with the same number of components.  Given two vectors A and B each with n components, the dot product is calculated as:

A · B = A1B1 + ... + AnBn

The dot product is thus the sum of the products of each component of the two vectors.  For example if A and B were 3D vectors:

A · B = A.x * B.x + A.y * B.y + A.z * B.z

The values |A| and |B| represent the lengths of vectors A and B, respectively, and Θ is the angle between the two vectors.  The dot product of vectors A and B will have the following relationship to these values:

a⋅b=∥a∥∥b∥cosθ

That is to say, the dot product of two vectors will be equal to the cosine of the angle between the vectors, times the lengths of each of the vectors.

In [33]:
print(v1.dot(v2))
print('Dot product without library ={}'.format(v1[0]*v2[0]+v1[1]*v2[1]))

14
Dot product without library =14


#### Dot product of two orthogal vectors is zero

Another way to interpret is that both are orthogonal to each other then cosθ will be zero. (i.e. cos90 = 0).
Dot product will also be zero if either of the vector is zero vector. 


In [35]:
v3 = np.array([1,0])
v4 = np.array([0,1])

print('Dot product of orthogonal vectors ={}'.format(v3.dot(v4)))

# |v3| = sqrt(1^2 + 0^2)
#print('Dot product using cosine formula ={}'.format(1.1.cos90))

Dot product of orthogonal vectors =0


### Cross Product

a X b=∥a∥∥b∥sinθ


In [38]:
v5 = np.array([1,2,3])
v6 = np.array([4,5,6])

print(np.cross(v5,v6))

[-3  6 -3]
